/* GENERATED by tools/build-free.js — do not edit.
   The free build: 100 foods with figures and traits, 482 more by name only,
   30 of 43 traits. Edit foods-data.js in the private repository
   and rebuild. */

const FODMAP_SERVES = {
  "Beet Root": {
    "low": 20,
    "note": "two slices",
    "src": "monash"
  },
  "Onion": {
    "low": 0,
    "note": "cooking, browning and straining do not remove fructans — they are water-soluble, not volatile",
    "src": "monash"
  },
  "Garlic": {
    "low": 0,
    "note": "garlic-infused oil is the usual way round it: fructans do not dissolve into oil",
    "src": "monash"
  },
  "Avocado": {
    "low": 30,
    "note": "sorbitol sets the limit",
    "src": "monash"
  },
  "Broccoli": {
    "low": 75,
    "note": "heads; the stalks are the fructan part",
    "src": "monash"
  },
  "White Button Mushrooms": {
    "low": 0,
    "note": "mannitol; canned button mushrooms rate low because the mannitol leaches into the brine",
    "src": "monash"
  },
  "Shiitake Mushrooms": {
    "low": 10,
    "src": "monash"
  },
  "Apples": {
    "low": 20,
    "src": "monash"
  },
  "Mangos": {
    "low": 40,
    "src": "monash"
  },
  "Raisins": {
    "low": 13,
    "note": "a tablespoon",
    "src": "monash"
  },
  "Almond": {
    "low": 12,
    "note": "ten almonds",
    "src": "monash"
  },
  "Peanut": {
    "low": 28,
    "src": "monash"
  },
  "Oats": {
    "low": 52,
    "note": "rolled, dry weight",
    "src": "monash"
  },
  "Pasta (no egg)": {
    "low": 74,
    "note": "cooked",
    "src": "monash"
  },
  "Chickpea (whole/flour)": {
    "low": 42,
    "note": "canned and drained; the GOS leaches into the liquid, so drained beats boiled",
    "src": "monash"
  },
  "Lentils": {
    "low": 46,
    "note": "canned and drained",
    "src": "monash"
  },
  "Cows Milk (3% fat)": {
    "low": 0,
    "note": "lactose; the lactose-free version is unrestricted",
    "src": "monash"
  },
  "Ice Cream": {
    "low": 0,
    "src": "monash"
  },
  "Milk chocolate": {
    "low": 20,
    "note": "four squares",
    "src": "monash"
  },
  "Honey": {
    "low": 7,
    "note": "a teaspoon",
    "src": "monash"
  },
  "Hummus": {
    "low": 20,
    "note": "a tablespoon",
    "src": "monash"
  }
};
