/* GENERATED by tools/build-free.js — do not edit.
   The free build: 100 foods with figures and traits, 482 more by name only,
   30 of 43 traits. Edit foods-data.js in the private repository
   and rebuild. */

const PORTION_BANDS = [
  {
    "band": 1,
    "label": "Up to 7g",
    "max": 7,
    "portion": 5,
    "example": "spices, salt, soy sauce, a knob of horseradish"
  },
  {
    "band": 2,
    "label": "7–17g",
    "max": 17,
    "portion": 15,
    "example": "oil, butter, a spoonful of seeds"
  },
  {
    "band": 3,
    "label": "17–35g",
    "max": 35,
    "portion": 25,
    "example": "a slice of cheese, a handful of nuts, dried fruit"
  },
  {
    "band": 4,
    "label": "35–69g",
    "max": 69,
    "portion": 50,
    "example": "a slice of bread, a bowl of berries, an egg, a pita"
  },
  {
    "band": 5,
    "label": "69–112g",
    "max": 112,
    "portion": 100,
    "example": "fruit, vegetables, mushrooms, a sausage"
  },
  {
    "band": 6,
    "label": "Over 112g",
    "max": null,
    "portion": 175,
    "example": "meat, fish, cooked grains, a glass of milk"
  }
];

function portionBand(grams) {
  for (let i = 0; i < PORTION_BANDS.length; i++) {
    const max = PORTION_BANDS[i].max;
    if (max == null || grams <= max) return PORTION_BANDS[i].band;
  }
  return PORTION_BANDS.length;
}

const TRAITS = {
  "fodmaps": {
    "order": 6,
    "label": "FODMAPs",
    "filter": true,
    "articleId": "fodmaps",
    "evidence": {
      "level": "Well established",
      "detail": "Multiple randomised trials in IBS, backed by breath testing and MRI work that shows the fermentation and water-drawing effects directly."
    },
    "analysis": [
      "These foods are high in FODMAPs — fermentable carbs that can cause gas, bloating, and discomfort. Usually mild, but more pronounced and slower to resolve in IBS.",
      "See the FODMAPs article for the specific subtypes and the low-FODMAP approach."
    ],
    "sv": {
      "label": "FODMAP",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Flera randomiserade studier vid IBS, med stöd av utandningstest och MR-undersökningar som visar jäsningen och vätskeindraget direkt."
      },
      "analysis": [
        "De här livsmedlen är rika på FODMAP — jäsbara kolhydrater som kan ge gaser, uppblåsthet och obehag. Oftast milt, men mer uttalat och långsammare att gå över vid IBS.",
        "Se artikeln om FODMAP för de enskilda undertyperna och lågFODMAP-metoden."
      ]
    }
  },
  "over_10g_fat": {
    "dose": true,
    "order": 1,
    "label": "Fat",
    "articleId": "fat",
    "evidence": {
      "level": "Well established",
      "detail": "Fat measurably slows gastric emptying and lowers the pressure of the lower esophageal sphincter. Symptom provocation is best documented in reflux and functional dyspepsia."
    },
    "analysis": [
      "A normal portion of these foods carries at least 6g of fat, which can worsen symptoms in GERD, IBS, gallbladder disease, and pancreatic insufficiency (EPI).",
      "See the Fat article for warning signs of malabsorption and who is most affected."
    ],
    "sv": {
      "label": "Fett",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Fett bromsar mätbart magsäckstömningen och sänker trycket i den nedre matstrupsmuskeln. Symtomprovokation är bäst dokumenterad vid reflux och funktionell dyspepsi."
      },
      "analysis": [
        "En normal portion av de här livsmedlen innehåller minst 6 g fett, vilket kan förvärra besvär vid GERD, IBS, gallbesvär och bukspottkörtelsvikt (EPI).",
        "Se artikeln om Fett för varningstecken på malabsorption och vilka som drabbas mest."
      ]
    }
  },
  "bile_stimulant": {
    "dose": true,
    "order": 8,
    "label": "Bile stimulant",
    "filter": true,
    "articleId": "bile_stimulant",
    "evidence": {
      "level": "Limited",
      "detail": "The CCK response to fat and protein is well measured, but the step from there to symptoms is inferred rather than trialled. The 9.5 g dose, and the fifth of its weight that protein counts for, are ours rather than published figures."
    },
    "analysis": [
      "These foods strongly stimulate bile release via CCK, mainly through fat and protein content. Most relevant for gallstones or a history of gallbladder attacks.",
      "See the Bile Stimulants article for clinical detail."
    ],
    "sv": {
      "label": "Gallstimulerande",
      "evidence": {
        "level": "Begränsat",
        "detail": "CCK-svaret på fett och protein är väl mätt, men steget därifrån till symtom är slutlett snarare än prövat. Dosen 9,5 g, och att protein räknas till en femtedel av sin vikt, är våra siffror och inte publicerade."
      },
      "analysis": [
        "De här livsmedlen stimulerar gallutsöndring kraftigt via CCK, främst genom sitt fett- och proteininnehåll. Mest relevant vid gallsten eller tidigare gallstensanfall.",
        "Se artikeln om Gallstimulerande för kliniska detaljer."
      ]
    }
  },
  "fiber": {
    "dose": true,
    "order": 4,
    "label": "Fiber",
    "filter": true,
    "articleId": "fiber",
    "evidence": {
      "level": "Well established",
      "detail": "A large trial base that cuts both ways: fiber relieves constipation and provokes bloating, and which one happens depends on the type and the person."
    },
    "analysis": [
      "These foods are high in fiber, which can cause gas and bloating at high intake, especially with dehydration or gut-microbial dysbiosis.",
      "See the Fiber article for benefits, sources, and the risks of a low-fiber diet."
    ],
    "sv": {
      "label": "Fiber",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Ett stort studieunderlag som pekar åt båda hållen: fiber lindrar förstoppning och framkallar uppblåsthet, och vilket det blir beror på typen och på personen."
      },
      "analysis": [
        "De här livsmedlen är fiberrika, vilket kan ge gaser och uppblåsthet vid högt intag, särskilt vid vätskebrist eller rubbad tarmflora.",
        "Se artikeln om Fiber för nyttan, källorna och riskerna med en fiberfattig kost."
      ]
    }
  },
  "protein": {
    "dose": true,
    "order": 2,
    "label": "Protein",
    "articleId": "protein",
    "evidence": {
      "level": "Limited",
      "detail": "Tracked as context rather than as a trigger. Protein itself rarely causes gut symptoms — what travels with it usually does."
    },
    "analysis": [
      "These foods are protein-rich. Protein moderately stimulates bile release and can add to digestive workload in large amounts. Symptoms are more often linked to what accompanies the protein (lactose, allergens, histamine) than protein itself, though pancreatitis, pancreatic tumors, and true food allergy can cause direct reactions."
    ],
    "sv": {
      "label": "Protein",
      "evidence": {
        "level": "Begränsat",
        "detail": "Följs som sammanhang snarare än som utlösare. Protein i sig ger sällan tarmbesvär — det som följer med gör det oftare."
      },
      "analysis": [
        "De här livsmedlen är proteinrika. Protein stimulerar gallutsöndring måttligt och kan öka matsmältningens arbete i stora mängder. Besvär hänger oftare ihop med det som följer med proteinet (laktos, allergener, histamin) än med proteinet självt — men pankreatit, tumörer i bukspottkörteln och äkta födoämnesallergi kan ge direkta reaktioner."
      ]
    }
  },
  "refined_carbs": {
    "order": 6,
    "label": "Refined carbs",
    "filter": true,
    "articleId": "refined_carbs",
    "evidence": {
      "level": "Limited",
      "detail": "A categorical tag by food type, not a measured threshold. The evidence links ultra-processed diets to gut symptoms at the level of the whole diet, not any single food."
    },
    "analysis": [
      "These foods are refined or ultra-processed carb sources — white bread, sugar, refined grains, and similar — rather than whole grains, legumes, or vegetables.",
      "This is a categorical tag based on food type and processing, not carbohydrate content."
    ],
    "sv": {
      "label": "Raffinerade kolhydrater",
      "evidence": {
        "level": "Begränsat",
        "detail": "En kategorisk märkning efter livsmedelstyp, inte ett mätt gränsvärde. Beläggen kopplar ultraprocessad kost till tarmbesvär på hela kostens nivå, inte något enskilt livsmedel."
      },
      "analysis": [
        "De här livsmedlen är raffinerade eller ultraprocessade kolhydratkällor — vitt bröd, socker, raffinerade spannmål och liknande — snarare än fullkorn, baljväxter eller grönsaker.",
        "Det här är en kategorisk märkning efter livsmedelstyp och bearbetning, inte efter kolhydratinnehåll."
      ]
    }
  },
  "over_3g_lactose": {
    "dose": true,
    "group": "FODMAPs",
    "order": 5,
    "label": "Lactose",
    "filter": true,
    "articleId": "lactose",
    "evidence": {
      "level": "Well established",
      "detail": "Hydrogen breath testing, genetic testing for lactase persistence and blinded dose-response trials. One of the best-characterised food intolerances there is."
    },
    "analysis": [
      "These foods are high in lactose, a milk sugar that can cause gas, bloating, and diarrhea in lactose-intolerant individuals, and discomfort in anyone at high intake.",
      "See the Lactose article for types, IBS overlap, and why new-onset intolerance in adults deserves investigation."
    ],
    "sv": {
      "label": "Laktos",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Utandningstest med väte, gentest för laktaspersistens och blindade dos-responsstudier. En av de bäst kartlagda födoämnesintoleranserna som finns."
      },
      "analysis": [
        "De här livsmedlen är laktosrika. Laktos är ett mjölksocker som kan ge gaser, uppblåsthet och diarré hos laktosintoleranta, och obehag hos vem som helst vid högt intag.",
        "Se artikeln om Laktos för typerna, överlappet med IBS och varför nydebuterad intolerans hos vuxna bör utredas."
      ]
    }
  },
  "histamine": {
    "order": 7,
    "label": "Histamine",
    "filter": true,
    "articleId": "histamine",
    "evidence": {
      "level": "Well established",
      "detail": "Measured histamine levels in food, and a well-characterised enzyme mechanism (DAO) for why it affects some people and not others."
    },
    "analysis": [
      "These foods either contain histamine or form it during fermentation, ripening or as freshness declines. The mechanism is well established: histamine is broken down by DAO in the gut, and where that enzyme activity is reduced, more of it reaches the bloodstream.",
      "Levels vary enormously between products and between batches — aged cheese runs from undetectable to nearly 400 mg/kg. Freshness and storage time often matter more than which food it is.",
      "Fermentation on its own is not enough of an explanation. Yogurt and fresh cheese are not tagged, because a short set with a defined starter culture never releases the free histidine that bacteria need as substrate."
    ],
    "sv": {
      "label": "Histamin",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Uppmätta histaminhalter i livsmedel, och en väl kartlagd enzymmekanism (DAO) för varför det påverkar vissa och inte andra."
      },
      "analysis": [
        "De här livsmedlen innehåller antingen histamin eller bildar det under fermentering, mognad eller när färskheten avtar. Mekanismen är väl belagd: histamin bryts ner av DAO i tarmen, och där enzymaktiviteten är nedsatt når mer av det blodet.",
        "Halterna varierar enormt mellan produkter och mellan satser — lagrad ost ligger allt från omätbart till nästan 400 mg/kg. Färskhet och lagringstid spelar ofta större roll än vilket livsmedel det är.",
        "Fermentering i sig räcker inte som förklaring. Yoghurt och färskost är inte taggade, eftersom en kort syrning med definierad startkultur aldrig frigör det fria histidin som bakterierna behöver som substrat."
      ]
    }
  },
  "dao_competitor": {
    "order": 12,
    "label": "DAO competitor",
    "filter": true,
    "articleId": "dao_competitor",
    "modifierOf": "histamine",
    "evidence": {
      "level": "Preliminary",
      "detail": "Test-tube enzyme assays and animal models only. No human studies, and no threshold for an effect has been established."
    },
    "analysis": [
      "These foods contain putrescine or cadaverine — diamines that compete with histamine for the same enzyme, DAO. They add no histamine of their own, but may in theory slow the breakdown of whatever histamine the meal does contain.",
      "This is the weakest-evidenced trait in the tool. It rests on enzyme assays in test tubes and on animal models; there are no human studies. No threshold for an effect has been established, and the effect appears to depend on the ratio between the amines rather than on the amount in any one food.",
      "Likely relevant only for particularly sensitive people, and only alongside histamine-rich food — which is why it is shown only when the selection also contains histamine. A food high in putrescine but without histamine has nothing to compete with."
    ],
    "sv": {
      "label": "DAO-hämmare",
      "evidence": {
        "level": "Preliminärt",
        "detail": "Enbart enzymanalyser i provrör och djurmodeller. Inga humanstudier, och ingen tröskel för effekt är fastställd."
      },
      "analysis": [
        "De här livsmedlen innehåller putrescin eller kadaverin — diaminer som konkurrerar med histamin om samma enzym, DAO. De tillför inget eget histamin, men kan i teorin bromsa nedbrytningen av det histamin måltiden ändå innehåller.",
        "Det här är verktygets svagast belagda tagg. Den vilar på enzymanalyser i provrör och på djurmodeller; humanstudier saknas. Ingen tröskel för effekt är fastställd, och effekten verkar bero på förhållandet mellan aminerna snarare än på mängden i något enskilt livsmedel.",
        "Sannolikt bara relevant för särskilt känsliga personer, och bara tillsammans med histaminrik mat — därför visas den bara när urvalet också innehåller histamin. Ett livsmedel med mycket putrescin men utan histamin har inget att konkurrera med."
      ]
    }
  },
  "salicylate": {
    "dose": true,
    "order": 13,
    "label": "Salicylates",
    "filter": true,
    "articleId": "salicylate",
    "evidence": {
      "level": "Limited",
      "detail": "One blinded dietary trial, negative overall, with a clear response in a single participant. Food levels come from one country's measurements and conflict with another's."
    },
    "analysis": [
      "These foods carry at least 1 mg of salicylic acid per normal portion. Salicylic acid is the same active principle as in aspirin, and sensitivity to it shows up as hives, itching, headache and gut symptoms.",
      "The only blinded dietary trial (Tuck 2021, n=10 in IBS) was negative overall. Clear symptom provocation appeared in a single participant — the one with known aspirin-induced urticaria — and a trend in one other. Estimated prevalence is around 2.5%.",
      "Ask about reactions to aspirin or NSAIDs. That is the phenotype where the signal actually sits, and a better way in than the food pattern itself.",
      "Preparation matters more than which food is chosen: peeling lowers the level three to fourfold and boiling lowers it, while pickling, marinating and concentrating raise it. The figures come from Australian measurements — a European study found no salicylates at all in Polish apple and pear varieties, and no Nordic data exists."
    ],
    "sv": {
      "label": "Salicylater",
      "evidence": {
        "level": "Begränsat",
        "detail": "En blindad koststudie, negativ som helhet, med tydligt svar hos en enda deltagare. Halterna i livsmedel kommer från ett lands mätningar och motsäger ett annat lands."
      },
      "analysis": [
        "De här livsmedlen innehåller minst 1 mg salicylsyra per normal portion. Salicylsyra är samma verksamma princip som i acetylsalicylsyra, och känslighet visar sig som nässelutslag, klåda, huvudvärk och tarmbesvär.",
        "Den enda blindade koststudien (Tuck 2021, n=10 vid IBS) var negativ som helhet. Tydlig symtomprovokation uppträdde hos en enda deltagare — den med känd acetylsalicylsyrautlöst urtikaria — och en tendens hos ytterligare en. Uppskattad förekomst ligger runt 2,5 %.",
        "Fråga om reaktioner på acetylsalicylsyra eller NSAID. Det är den fenotyp där signalen faktiskt finns, och en bättre ingång än kostmönstret i sig.",
        "Tillagningen spelar större roll än vilket livsmedel som väljs: skalning sänker halten tre till fyra gånger och kokning sänker den, medan inläggning, marinering och koncentrering höjer den. Siffrorna kommer från australiska mätningar — en europeisk studie hittade inga salicylater alls i polska äppel- och päronsorter, och nordiska data saknas."
      ]
    }
  },
  "alcohol": {
    "dose": true,
    "group": "GI Irritants",
    "order": 6,
    "label": "Alcohol",
    "filter": true,
    "evidence": {
      "level": "Well established",
      "detail": "The mucosal effect and the sphincter relaxation are both measured. How much it takes to produce symptoms is less settled than the mechanism."
    },
    "analysis": [
      "These foods or drinks contain alcohol, which can directly irritate the gut lining, relax the lower esophageal sphincter (worsening reflux), and affect liver and pancreatic function with regular high intake."
    ],
    "sv": {
      "label": "Alkohol",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Både slemhinnepåverkan och avslappningen av matstrupsmuskeln är uppmätta. Hur mycket som krävs för att ge besvär är mindre klarlagt än mekanismen."
      },
      "analysis": [
        "De här livsmedlen eller dryckerna innehåller alkohol, som direkt kan irritera tarmslemhinnan, slappna av den nedre matstrupsmuskeln (och förvärra reflux) samt påverka lever- och bukspottkörtelfunktion vid regelbundet högt intag."
      ]
    }
  },
  "caffeine": {
    "group": "GI Irritants",
    "order": 7,
    "label": "Caffeine",
    "filter": true,
    "evidence": {
      "level": "Well established",
      "detail": "Measured effects on colonic motility and acid secretion. Whether that becomes a symptom varies widely between people."
    },
    "analysis": [
      "These foods or drinks contain caffeine, which stimulates gut motility and acid secretion and can worsen symptoms in people with IBS, GERD, or general gut sensitivity."
    ],
    "sv": {
      "label": "Koffein",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Uppmätta effekter på tjocktarmens motorik och på syrasekretionen. Om det blir ett symtom varierar stort mellan personer."
      },
      "analysis": [
        "De här livsmedlen eller dryckerna innehåller koffein, som stimulerar tarmmotoriken och syrasekretionen och kan förvärra besvär vid IBS, GERD eller allmän tarmkänslighet."
      ]
    }
  },
  "irritant": {
    "order": 5,
    "label": "Irritant",
    "filter": true,
    "articleId": "irritant",
    "evidence": {
      "level": "Limited",
      "detail": "An umbrella over mechanisms that range from well measured to clinical experience alone. The specific traits underneath carry their own levels."
    },
    "analysis": [
      "These foods can worsen symptoms across GERD, IBS, gallbladder disease, and general gut sensitivity through varied mechanisms — some well-established, others based on clinical experience.",
      "See the GI Irritants article for the specific mechanisms tracked separately."
    ],
    "sv": {
      "label": "Irriterande",
      "evidence": {
        "level": "Begränsat",
        "detail": "Ett paraply över mekanismer som spänner från väl uppmätta till enbart klinisk erfarenhet. De specifika taggarna under bär sina egna nivåer."
      },
      "analysis": [
        "De här livsmedlen kan förvärra besvär vid GERD, IBS, gallbesvär och allmän tarmkänslighet genom skiftande mekanismer — vissa väl belagda, andra grundade på klinisk erfarenhet.",
        "Se artikeln om Tarmirriterande ämnen för de mekanismer som följs var för sig."
      ]
    }
  },
  "allergen_milk": {
    "group": "Allergens",
    "order": 1,
    "label": "Milk",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Casein and whey are well-characterised allergens with standardised diagnostic testing."
    },
    "analysis": [
      "Cow's milk allergy is mediated mainly by casein and whey proteins — distinct from lactose intolerance, which is a digestive enzyme issue, not an immune one."
    ],
    "sv": {
      "label": "Mjölk",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Kasein och vassle är väl kartlagda allergener med standardiserad diagnostik."
      },
      "analysis": [
        "Komjölksallergi förmedlas främst av kasein- och vassleproteiner — skilt från laktosintolerans, som är ett enzymproblem i matsmältningen och inte immunologiskt."
      ]
    }
  },
  "allergen_egg": {
    "group": "Allergens",
    "order": 2,
    "label": "Egg",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Ovalbumin and ovomucoid are well characterised, and ovomucoid testing predicts whether baked egg is tolerated."
    },
    "analysis": [
      "Egg allergy is mediated mainly by proteins in the egg white (ovalbumin, ovomucoid). The yolk is less allergenic but not necessarily safe for someone with an egg allergy."
    ],
    "sv": {
      "label": "Ägg",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Ovalbumin och ovomukoid är väl kartlagda, och ovomukoidtest förutsäger om bakat ägg tolereras."
      },
      "analysis": [
        "Äggallergi förmedlas främst av proteiner i äggvitan (ovalbumin, ovomukoid). Gulan är mindre allergen men inte nödvändigtvis säker för någon med äggallergi."
      ]
    }
  },
  "allergen_wheat": {
    "group": "Allergens",
    "order": 3,
    "label": "Gluten cereals",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Well-characterised allergen proteins with standardised testing, distinct from celiac disease and from gluten sensitivity."
    },
    "analysis": [
      "The EU declares wheat, rye, barley, oats, spelt and kamut as one group. Wheat allergy is an immune reaction to wheat proteins — distinct from celiac disease and from non-celiac gluten sensitivity, which are not classic IgE-mediated allergies."
    ],
    "sv": {
      "label": "Glutenspannmål",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Väl kartlagda allergenproteiner med standardiserad diagnostik, skilt från celiaki och från glutenkänslighet."
      },
      "analysis": [
        "EU deklarerar vete, råg, korn, havre, dinkel och kamut som en grupp. Veteallergi är en immunreaktion mot veteproteiner — skilt från celiaki och från icke-celiakisk glutenkänslighet, som inte är klassiska IgE-medierade allergier."
      ]
    }
  },
  "allergen_fish": {
    "group": "Allergens",
    "order": 4,
    "label": "Fish",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Parvalbumin is well characterised, and component testing separates fish from shellfish allergy."
    },
    "analysis": [
      "Fish allergy is mediated mainly by parvalbumin, a muscle protein — a different allergen than shellfish tropomyosin, so an allergy to one doesn't necessarily mean an allergy to the other."
    ],
    "sv": {
      "label": "Fisk",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Parvalbumin är väl kartlagt, och komponenttest skiljer fiskallergi från skaldjursallergi."
      },
      "analysis": [
        "Fiskallergi förmedlas främst av parvalbumin, ett muskelprotein — ett annat allergen än skaldjurens tropomyosin, så allergi mot det ena innebär inte nödvändigtvis allergi mot det andra."
      ]
    }
  },
  "allergen_crustacean": {
    "group": "Allergens",
    "order": 5,
    "label": "Crustaceans",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Tropomyosin is well characterised and testable."
    },
    "analysis": [
      "Shrimp, crab, lobster and crayfish. The allergen is tropomyosin, which is why a reaction to one crustacean usually means a reaction to the others.",
      "Molluscs carry a related but distinct tropomyosin and are declared separately in the EU — many people react to one group and not the other."
    ],
    "sv": {
      "label": "Kräftdjur",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Tropomyosin är väl kartlagt och testbart."
      },
      "analysis": [
        "Räka, krabba, hummer och kräfta. Allergenet är tropomyosin, vilket är varför en reaktion på ett kräftdjur oftast betyder reaktion på de andra.",
        "Blötdjur bär ett besläktat men skilt tropomyosin och deklareras separat i EU — många reagerar på den ena gruppen men inte den andra."
      ]
    }
  },
  "allergen_mollusc": {
    "group": "Allergens",
    "order": 6,
    "label": "Molluscs",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "A declarable allergen in its own right, with tropomyosin again the main protein."
    },
    "analysis": [
      "Mussels, oysters, squid and snails. The tropomyosin here differs enough from the crustacean version that the two are declared separately and often tolerated separately."
    ],
    "sv": {
      "label": "Blötdjur",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Ett deklarationspliktigt allergen i egen rätt, med tropomyosin återigen som huvudprotein."
      },
      "analysis": [
        "Musslor, ostron, bläckfisk och sniglar. Tropomyosinet här skiljer sig tillräckligt från kräftdjurens för att de två ska deklareras separat och ofta tolereras separat."
      ]
    }
  },
  "allergen_peanut": {
    "group": "Allergens",
    "order": 7,
    "label": "Peanut",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Among the most studied of all allergens, with component testing (Ara h 2) and an established immunotherapy."
    },
    "analysis": [
      "Peanut allergy is one of the most common severe food allergies. Peanut is a legume, not a tree nut, and peanut allergy doesn't reliably predict tree nut allergy."
    ],
    "sv": {
      "label": "Jordnöt",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Bland de mest studerade av alla allergener, med komponenttest (Ara h 2) och etablerad immunterapi."
      },
      "analysis": [
        "Jordnötsallergi är en av de vanligaste svåra födoämnesallergierna. Jordnöt är en baljväxt, inte en trädnöt, och jordnötsallergi förutsäger inte tillförlitligt allergi mot trädnötter."
      ]
    }
  },
  "allergen_treenut": {
    "group": "Allergens",
    "order": 8,
    "label": "Tree nut",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Well-characterised proteins, with component testing that separates the individual nuts."
    },
    "analysis": [
      "Tree nut allergy (almond, cashew, walnut, hazelnut, Brazil nut, etc.) is botanically and clinically distinct from peanut allergy."
    ],
    "sv": {
      "label": "Trädnöt",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Väl kartlagda proteiner, med komponenttest som skiljer de enskilda nötterna åt."
      },
      "analysis": [
        "Trädnötsallergi (mandel, cashew, valnöt, hasselnöt, paranöt med flera) är botaniskt och kliniskt skild från jordnötsallergi."
      ]
    }
  },
  "allergen_soy": {
    "group": "Allergens",
    "order": 9,
    "label": "Soy",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Well characterised, though soy allergy is diagnosed less consistently than the others."
    },
    "analysis": [
      "Soy allergy is mediated by several soy proteins and can occasionally cross-react with peanut, since both are legumes."
    ],
    "sv": {
      "label": "Soja",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Väl kartlagt, även om sojaallergi diagnostiseras mindre enhetligt än de övriga."
      },
      "analysis": [
        "Sojaallergi förmedlas av flera sojaproteiner och kan ibland korsreagera med jordnöt, eftersom båda är baljväxter."
      ]
    }
  },
  "allergen_sesame": {
    "group": "Allergens",
    "order": 10,
    "label": "Sesame",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "A recognised major allergen with standardised testing. The labelling requirement is newer than the evidence behind it."
    },
    "analysis": [
      "Sesame can cause severe reactions and hides easily — in tahini, in bread toppings, and in oils that are not always declared on a menu."
    ],
    "sv": {
      "label": "Sesam",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Ett erkänt huvudallergen med standardiserad diagnostik. Märkningskravet är nyare än beläggen bakom det."
      },
      "analysis": [
        "Sesam kan ge svåra reaktioner och göms lätt — i tahini, i brödtoppingar och i oljor som inte alltid deklareras på en meny."
      ]
    }
  },
  "allergen_celery": {
    "group": "Allergens",
    "order": 11,
    "label": "Celery",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Declarable in the EU and rarely so elsewhere. Component testing exists (Api g 1), and the birch link is well documented."
    },
    "analysis": [
      "Celery and celeriac are declarable allergens in the EU but not in the US, which is why they are missed more often than their prevalence warrants.",
      "Much of it runs through birch pollen: Api g 1 belongs to the same PR-10 family as the birch allergen, so celery reactions often appear in people who already react to apple and hazelnut. Unlike most PR-10 reactions, celery can also react when cooked."
    ],
    "sv": {
      "label": "Selleri",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Deklarationspliktigt i EU och sällan någon annanstans. Komponenttest finns (Api g 1), och björkkopplingen är väl dokumenterad."
      },
      "analysis": [
        "Selleri och rotselleri är deklarationspliktiga allergener i EU men inte i USA, vilket är varför de missas oftare än förekomsten motiverar.",
        "Mycket av det går via björkpollen: Api g 1 tillhör samma PR-10-familj som björkallergenet, så sellerireaktioner dyker ofta upp hos personer som redan reagerar på äpple och hasselnöt. Till skillnad från de flesta PR-10-reaktioner kan selleri reagera även tillagad."
      ]
    }
  },
  "allergen_mustard": {
    "group": "Allergens",
    "order": 12,
    "label": "Mustard",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Well established",
      "detail": "Declarable in the EU, with characterised seed proteins. Prevalence is low but reactions can be severe."
    },
    "analysis": [
      "Mustard is a declarable allergen in the EU. Reactions are uncommon but can be severe, and mustard turns up unannounced in dressings, remoulade, sausage and spice blends."
    ],
    "sv": {
      "label": "Senap",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Deklarationspliktigt i EU, med kartlagda fröproteiner. Förekomsten är låg men reaktionerna kan bli svåra."
      },
      "analysis": [
        "Senap är ett deklarationspliktigt allergen i EU. Reaktioner är ovanliga men kan bli svåra, och senap dyker upp oanmält i dressingar, remoulad, korv och kryddblandningar."
      ]
    }
  },
  "allergen_sulphite": {
    "order": 20,
    "label": "Sulphites",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Limited",
      "detail": "Declarable above 10 mg/kg, and the asthma link is documented. Outside asthma the picture is thinner, and the mechanism is not IgE."
    },
    "analysis": [
      "Sulphites are declarable above 10 mg/kg. They are preservatives rather than proteins, so the reaction is not a true allergy — the best documented one is bronchoconstriction in people with asthma.",
      "Wine, dried fruit that has kept its colour, and some pickled products are the usual sources."
    ],
    "sv": {
      "label": "Sulfiter",
      "evidence": {
        "level": "Begränsat",
        "detail": "Deklarationspliktigt över 10 mg/kg, och astmakopplingen är dokumenterad. Utanför astma är bilden tunnare, och mekanismen är inte IgE."
      },
      "analysis": [
        "Sulfiter är deklarationspliktiga över 10 mg/kg. De är konserveringsmedel och inte proteiner, så reaktionen är ingen äkta allergi — den bäst dokumenterade är luftrörssammandragning hos personer med astma.",
        "Vin, torkad frukt som behållit färgen och vissa inlagda produkter är de vanliga källorna."
      ]
    }
  },
  "allergen_onion": {
    "group": "Allergens",
    "order": 13,
    "label": "Onion & garlic",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Limited",
      "detail": "Case reports and skin-prick data, no population studies. The overlap with fructan intolerance makes it hard to separate the two."
    },
    "analysis": [
      "Allium allergy — onion, garlic, leek, shallot — is not declarable anywhere, so nothing on a label warns about it.",
      "It is easily confused with the fructan intolerance these foods also cause, and the two need different answers: fructans are dose-dependent and cooking does not help, while an allergy is not. If onion and garlic keep appearing, check whether the reaction is immediate and oral, or delayed and abdominal."
    ],
    "sv": {
      "label": "Lök och vitlök",
      "evidence": {
        "level": "Begränsat",
        "detail": "Fallrapporter och pricktestdata, inga populationsstudier. Överlappet med fruktanintolerans gör de två svåra att skilja åt."
      },
      "analysis": [
        "Allium-allergi — lök, vitlök, purjolök, schalottenlök — är inte deklarationspliktig någonstans, så ingenting på en förpackning varnar för den.",
        "Den förväxlas lätt med den fruktanintolerans som samma livsmedel också ger, och de två behöver olika svar: fruktaner är dosberoende och tillagning hjälper inte, medan en allergi inte är det. Om lök och vitlök återkommer, kolla om reaktionen är omedelbar och i munnen, eller fördröjd och i magen."
      ]
    }
  },
  "allergen_mushroom": {
    "group": "Allergens",
    "order": 14,
    "label": "Mushroom",
    "filter": true,
    "articleId": "allergen",
    "evidence": {
      "level": "Limited",
      "detail": "Documented in case series and occupational studies, mostly as inhalant sensitisation to spores. Food reactions are reported but rarely confirmed by challenge."
    },
    "analysis": [
      "Mushroom allergy is not declarable, and most of what is documented concerns spore inhalation rather than eating them.",
      "Mycoprotein products such as Quorn belong here too: they are made from a fungus, and reactions have been reported in people with no other food allergy."
    ],
    "sv": {
      "label": "Svamp",
      "evidence": {
        "level": "Begränsat",
        "detail": "Dokumenterat i fallserier och yrkesstudier, mest som inhalationssensibilisering mot sporer. Reaktioner på att äta svamp rapporteras men bekräftas sällan med provokation."
      },
      "analysis": [
        "Svampallergi är inte deklarationspliktig, och det mesta som är dokumenterat gäller inandning av sporer snarare än att äta svampen.",
        "Mykoproteinprodukter som Quorn hör hit också: de görs av en svamp, och reaktioner har rapporterats hos personer utan annan födoämnesallergi."
      ]
    }
  },
  "cross_reactive": {
    "order": 10,
    "label": "Cross-reaction",
    "filter": true,
    "articleId": "cross_reactive",
    "evidence": {
      "level": "Well established",
      "detail": "Oral allergy syndrome is well documented and the shared protein families are identified and testable. Which foods trigger it varies by person and by pollen season."
    },
    "analysis": [
      "These foods can trigger oral allergy syndrome (OAS) in people allergic to certain pollens, due to structurally similar proteins. Reactions are usually mild and often resolve with cooking.",
      "See the Cross-Reactivity article for the three pollen groups."
    ],
    "sv": {
      "label": "Korsreaktion",
      "evidence": {
        "level": "Väl belagt",
        "detail": "Oralt allergisyndrom är väl dokumenterat och de gemensamma proteinfamiljerna är identifierade och testbara. Vilka livsmedel som utlöser varierar med person och pollensäsong."
      },
      "analysis": [
        "De här livsmedlen kan utlösa oralt allergisyndrom (OAS) hos personer med vissa pollenallergier, på grund av strukturellt liknande proteiner. Reaktionerna är oftast milda och försvinner ofta vid tillagning.",
        "Se artikeln om Korsreaktivitet för de tre pollengrupperna."
      ]
    }
  },
  "alpha_gal": {
    "order": 11,
    "label": "Alpha-gal syndrome",
    "filter": true,
    "articleId": "alpha_gal",
    "evidence": {
      "level": "Well established",
      "detail": "IgE to alpha-gal is measurable, the tick-bite route is established, and the delayed reaction has been reproduced under challenge."
    },
    "analysis": [
      "These foods are mammalian meat, which can trigger a delayed allergic reaction (alpha-gal syndrome) in people sensitized by a prior tick bite. Reactions often appear 3-8 hours after eating, making the food link easy to miss.",
      "See the Alpha-Gal Syndrome article for the tick-bite mechanism and diagnostic testing."
    ],
    "sv": {
      "label": "Alfa-gal-syndrom",
      "evidence": {
        "level": "Väl belagt",
        "detail": "IgE mot alfa-gal är mätbart, fästingvägen är etablerad, och den fördröjda reaktionen har återskapats vid provokation."
      },
      "analysis": [
        "De här livsmedlen är kött från däggdjur, som kan utlösa en fördröjd allergisk reaktion (alfa-gal-syndrom) hos personer som sensibiliserats av ett tidigare fästingbett. Reaktionerna kommer ofta 3–8 timmar efter måltiden, vilket gör kopplingen till maten lätt att missa.",
        "Se artikeln om Alfa-gal-syndrom för fästingmekanismen och diagnostiken."
      ]
    }
  }
};

const FILTER_SECTIONS = [
  {
    "title": "GI Irritants",
    "sv": "GI-irriterande",
    "noun": "irritant",
    "svNoun": "irriterande ämne",
    "svNounTypes": "irritanttyper",
    "svGender": "ett",
    "broad": "irritant",
    "group": "GI Irritants"
  },
  {
    "title": "FODMAPs",
    "sv": "FODMAP",
    "noun": "FODMAP",
    "svNoun": "FODMAP",
    "svNounTypes": "FODMAP-typer",
    "svGender": "en",
    "broad": "fodmaps",
    "group": "FODMAPs"
  },
  {
    "title": "Other Digestive Factors",
    "sv": "Övriga matsmältningsfaktorer",
    "items": [
      "fiber",
      "histamine",
      "dao_competitor",
      "salicylate",
      "bile_stimulant",
      "refined_carbs",
      "allergen_sulphite"
    ]
  },
  {
    "title": "Allergens",
    "sv": "Allergener",
    "noun": "allergen",
    "svNoun": "allergen",
    "svNounTypes": "allergentyper",
    "svGender": "ett",
    "group": "Allergens",
    "wide": true
  },
  {
    "title": "Cross-Reactivity & Delayed Allergy",
    "sv": "Korsreaktivitet & fördröjd allergi",
    "noun": "cross-reaction",
    "svNoun": "korsreaktion",
    "svNounTypes": "korsreaktionstyper",
    "svGender": "en",
    "broad": "cross_reactive",
    "group": "Cross-reactivity",
    "items": [
      "alpha_gal"
    ],
    "wide": true
  }
];

const CATEGORIES = [
  {
    id: "veggies",
    label: "Vegetables",
    sv: "Grönsaker",
    foods: [
      { name: "Cabbage", sv: "Vitkål", locked: true },
      { name: "Kale", sv: "Grönkål", locked: true },
      { name: "Onion", sv: "Gul lök", lmv: "Lök gul", portion: 60, traits: ["fodmaps", "irritant", "allergen_onion"] },
      { name: "Tomato", sv: "Tomat", form: "fresh", lmv: "Tomat", portion: 100, traits: ["histamine", "irritant", "cross_reactive", "dao_competitor"] },
      { name: "Sun-dried Tomato", sv: "Soltorkad tomat", locked: true },
      { name: "Cauliflower", sv: "Blomkål", locked: true },
      { name: "Aubergine", sv: "Aubergine", locked: true },
      { name: "Parsley", sv: "Persilja", locked: true },
      { name: "Leek", sv: "Purjolök", locked: true },
      { name: "Spinach", sv: "Spenat", locked: true },
      { name: "Avocado", sv: "Avokado", lmv: "Avokado", portion: 50, traits: ["over_10g_fat", "bile_stimulant", "cross_reactive", "fodmaps", "salicylate"] },
      { name: "Cucumber", sv: "Gurka", locked: true },
      { name: "Bell Pepper (sweet)", sv: "Paprika (söt)", locked: true },
      { name: "Bell Pepper (hot)", sv: "Chilipeppar", locked: true },
      { name: "Asparagus", sv: "Sparris", locked: true },
      { name: "Fennel Bulb", sv: "Fänkål", locked: true },
      { name: "Broccoli", sv: "Broccoli", lmv: "Broccoli", portion: 100, traits: ["fodmaps"] },
      { name: "Brussels Sprouts", sv: "Brysselkål", locked: true },
      { name: "Green Beans", sv: "Haricots verts", locked: true },
      { name: "Zucchini", sv: "Squash", locked: true },
      { name: "Pumpkin", sv: "Pumpa", locked: true },
      { name: "Swiss Chard", sv: "Mangold", locked: true },
      { name: "Romaine Lettuce", sv: "Romansallat", locked: true },
      { name: "Rocket", sv: "Ruccola", locked: true },
      { name: "Celery", sv: "Stjälkselleri", locked: true },
      { name: "Bok Choy", sv: "Pak choi", locked: true },
      { name: "Daikon Radish", sv: "Rättika", locked: true },
      { name: "Rhubarb", sv: "Rabarber", locked: true },
      { name: "Sweetcorn", sv: "Majs", locked: true },
      { name: "Shallot", sv: "Schalottenlök", locked: true },
      { name: "Spring Onion", sv: "Salladslök", locked: true },
      { name: "Globe Artichoke", sv: "Kronärtskocka", locked: true },
      { name: "Okra", sv: "Okra", locked: true }
    ]
  },
  {
    id: "fruits",
    label: "Fruits",
    sv: "Frukt",
    foods: [
      { name: "Apples", sv: "Äpple", lmv: "Äpple m. skal", portion: 100, traits: ["fodmaps", "irritant", "cross_reactive", "salicylate"] },
      { name: "Oranges", sv: "Apelsin", lmv: "Apelsin", portion: 100, traits: ["cross_reactive", "dao_competitor"] },
      { name: "Pears", sv: "Päron", locked: true },
      { name: "Mangos", sv: "Mango", lmv: "Mango", portion: 100, traits: ["fodmaps", "cross_reactive"] },
      { name: "Lemon", sv: "Citron", locked: true },
      { name: "Lime", sv: "Lime", locked: true },
      { name: "Grapefruit", sv: "Grapefrukt", locked: true },
      { name: "Grapes", sv: "Vindruvor", locked: true },
      { name: "Banana", sv: "Banan", lmv: "Banan", portion: 100, traits: ["cross_reactive", "dao_competitor"] },
      { name: "Kiwi", sv: "Kiwi", locked: true },
      { name: "Pineapple", sv: "Ananas", locked: true },
      { name: "Papaya", sv: "Papaya", locked: true },
      { name: "Watermelon", sv: "Vattenmelon", locked: true },
      { name: "Melon", sv: "Melon", locked: true },
      { name: "Apricot", sv: "Aprikos", locked: true },
      { name: "Plum", sv: "Plommon", locked: true },
      { name: "Figs", sv: "Fikon", locked: true },
      { name: "Pomegranate", sv: "Granatäpple", locked: true },
      { name: "Lychee", sv: "Litchi", locked: true },
      { name: "Star Fruit", sv: "Stjärnfrukt", locked: true },
      { name: "Durian", sv: "Durian", locked: true },
      { name: "Peach", sv: "Persika", locked: true },
      { name: "Nectarine", sv: "Nektarin", locked: true },
      { name: "Passion Fruit", sv: "Passionsfrukt", locked: true },
      { name: "Persimmon", sv: "Persimon", locked: true },
      { name: "Canned Peaches in Syrup", sv: "Persika i sockerlag", locked: true },
      { name: "Canned Pears in Syrup", sv: "Päron i sockerlag", locked: true },
      { name: "Canned Pineapple in Syrup", sv: "Ananas i sockerlag", locked: true },
      { name: "Canned Apricots in Syrup", sv: "Aprikos i sockerlag", locked: true }
    ]
  },
  {
    id: "driedFruits",
    label: "Dried Fruit & Berries",
    sv: "Torkad frukt och bär",
    foods: [
      { name: "Dates", sv: "Dadlar", locked: true },
      { name: "Raisins", sv: "Russin", lmv: "Russin", portion: 30, traits: ["fodmaps"] },
      { name: "Sultanas", sv: "Sultanrussin", locked: true },
      { name: "Dried Apricot", sv: "Torkad aprikos", lmv: "Aprikos torkad", portion: 30, traits: ["cross_reactive", "fodmaps", "allergen_sulphite"] },
      { name: "Dried Fig", sv: "Torkat fikon", locked: true },
      { name: "Prunes", sv: "Katrinplommon", lmv: "Katrinplommon torkade", portion: 30, traits: ["cross_reactive", "fodmaps"] },
      { name: "Dried Cranberry (Added Sugar)", sv: "Torkade tranbär (sötade)", locked: true },
      { name: "Dried Cranberry (No Sugar Added)", sv: "Torkade tranbär (osötade)", locked: true },
      { name: "Dried Mango (Added Sugar)", sv: "Torkad mango (sötad)", locked: true },
      { name: "Dried Mango (No Sugar Added)", sv: "Torkad mango (osötad)", locked: true },
      { name: "Dried Pineapple (Added Sugar)", sv: "Torkad ananas (sötad)", locked: true },
      { name: "Dried Pineapple (No Sugar Added)", sv: "Torkad ananas (osötad)", locked: true },
      { name: "Dried Papaya (Added Sugar)", sv: "Torkad papaya (sötad)", locked: true },
      { name: "Dried Papaya (No Sugar Added)", sv: "Torkad papaya (osötad)", locked: true },
      { name: "Dried Banana", sv: "Torkad banan", locked: true },
      { name: "Dried Apple", sv: "Torkat äpple", locked: true },
      { name: "Dried Pear", sv: "Torkat päron", locked: true },
      { name: "Dried Blueberries (Added Sugar)", sv: "Torkade blåbär (sötade)", locked: true },
      { name: "Dried Blueberries (No Sugar Added)", sv: "Torkade blåbär (osötade)", locked: true },
      { name: "Dried Peach", sv: "Torkad persika", locked: true },
      { name: "Dried Coconut", sv: "Torkad kokos", locked: true },
      { name: "Dried Goji Berry", sv: "Torkade gojibär", locked: true },
      { name: "Dried Kiwi (Added Sugar)", sv: "Torkad kiwi (sötad)", locked: true },
      { name: "Dried Kiwi (No Sugar Added)", sv: "Torkad kiwi (osötad)", locked: true },
      { name: "Dried Tropical Fruit Mix", sv: "Torkad tropisk fruktmix", locked: true }
    ]
  },
  {
    id: "berries",
    label: "Berries",
    sv: "Bär",
    foods: [
      { name: "Canned Cherries in Syrup", sv: "Körsbär i sockerlag", locked: true },
      { name: "Canned Strawberries in Syrup", sv: "Jordgubbar i sockerlag", locked: true },
      { name: "Blueberry", sv: "Blåbär", lmv: "Blåbär", portion: 50, traits: [] },
      { name: "Strawberry", sv: "Jordgubbe", lmv: "Jordgubbar", portion: 50, traits: ["salicylate"] },
      { name: "Cherries", sv: "Körsbär", locked: true },
      { name: "Blackberries", sv: "Björnbär", locked: true },
      { name: "Raspberries", sv: "Hallon", lmv: "Hallon", portion: 50, traits: [] },
      { name: "Cloudberries", sv: "Hjortron", locked: true },
      { name: "Lingonberry", sv: "Lingon", locked: true },
      { name: "Redcurrant", sv: "Röda vinbär", locked: true },
      { name: "Blackcurrant", sv: "Svarta vinbär", locked: true },
      { name: "Gooseberry", sv: "Krusbär", locked: true },
      { name: "Elderberry", sv: "Fläderbär", locked: true },
      { name: "Cranberry", sv: "Tranbär", locked: true },
      { name: "Sea Buckthorn", sv: "Havtorn", locked: true },
      { name: "Aronia", sv: "Aronia", locked: true },
      { name: "Mulberry", sv: "Mullbär", locked: true },
      { name: "Physalis", sv: "Physalis", locked: true },
      { name: "Frozen Mixed Berries", sv: "Frysta blandade bär", locked: true }
    ]
  },
  {
    id: "roots",
    label: "Roots & Tubers",
    sv: "Rotfrukter",
    foods: [
      { name: "Beet Root", sv: "Rödbeta", lmv: "Rödbeta", portion: 80, traits: ["fodmaps", "salicylate"] },
      { name: "Carrot", sv: "Morot", lmv: "Morot", portion: 80, traits: ["cross_reactive"] },
      { name: "Celeriac Root", sv: "Rotselleri", locked: true },
      { name: "Jerusalem Artichoke", sv: "Jordärtskocka", locked: true },
      { name: "Parsnip", sv: "Palsternacka", locked: true },
      { name: "Potato", sv: "Potatis", lmv: "Potatis rå", portion: 175, traits: ["cross_reactive"] },
      { name: "Swede", sv: "Kålrot", locked: true },
      { name: "Sweet Potato", sv: "Sötpotatis", locked: true },
      { name: "Radish", sv: "Rädisa", locked: true },
      { name: "Turnip", sv: "Rova", locked: true },
      { name: "Horseradish", sv: "Pepparrot", locked: true },
      { name: "Black Salsify", sv: "Svartrot", locked: true },
      { name: "Kohlrabi", sv: "Kålrabbi", locked: true },
      { name: "Cassava", sv: "Kassava", locked: true },
      { name: "Yam", sv: "Jams", locked: true },
      { name: "Taro", sv: "Taro", locked: true },
      { name: "Lotus Root", sv: "Lotusrot", locked: true }
    ]
  },
  {
    id: "mushrooms",
    label: "Mushrooms",
    sv: "Svamp",
    foods: [
      { name: "Shiitake Mushrooms", sv: "Shiitakesvamp", form: "fresh", lmv: "Shiitakesvamp", portion: 80, traits: ["fodmaps", "dao_competitor", "allergen_mushroom"] },
      { name: "Oyster Mushrooms", sv: "Ostronskivling", locked: true },
      { name: "White Button Mushrooms", sv: "Champinjon", form: "fresh", lmv: "Champinjon", portion: 80, traits: ["fodmaps", "dao_competitor", "allergen_mushroom"] },
      { name: "Portobello Mushrooms", sv: "Portabello", locked: true },
      { name: "Cremini Mushrooms", sv: "Kastanjechampinjon", locked: true },
      { name: "Chanterelle Mushrooms", sv: "Kantarell", form: "fresh", lmv: "Kantarell gul rå", portion: 80, traits: ["fodmaps", "dao_competitor", "allergen_mushroom"] },
      { name: "Porcini Mushrooms", sv: "Karljohansvamp", locked: true },
      { name: "Morel Mushrooms", sv: "Murkla", locked: true },
      { name: "King Oyster Mushrooms", sv: "Kungsostronskivling", locked: true },
      { name: "Truffle", sv: "Tryffel", locked: true },
      { name: "Maitake Mushrooms", sv: "Maitake", locked: true }
    ]
  },
  {
    id: "grains",
    label: "Grains & Flours",
    sv: "Spannmål och mjöl",
    foods: [
      { name: "Oats", sv: "Havre", form: "dry", lmv: "Havregryn fullkorn", portion: 40, traits: ["fodmaps", "allergen_wheat"] },
      { name: "Oat Porridge", sv: "Havregrynsgröt", locked: true },
      { name: "Oat Bran", sv: "Havrekli", locked: true },
      { name: "Muesli (no added sugar)", sv: "Müsli (utan tillsatt socker)", locked: true },
      { name: "Wheat", sv: "Vete", form: "cooked", lmv: "Matvete kokt m. salt", portion: 175, traits: ["fiber", "fodmaps", "allergen_wheat"] },
      { name: "Rye", sv: "Råg", form: "dry", lmv: "Rågkross ångprep. fullkorn", lmvNote: "cracked whole grain, dry weight — rye is not listed cooked", portion: 60, traits: ["fiber", "fodmaps", "allergen_wheat"] },
      { name: "Pearl Barley (cooked)", sv: "Korngryn (kokta)", locked: true },
      { name: "Barley", sv: "Korn", locked: true },
      { name: "Quinoa", sv: "Quinoa", locked: true },
      { name: "Buckwheat", sv: "Bovete", locked: true },
      { name: "Rice", sv: "Ris", form: "cooked", lmv: "Ris råris kokt m. salt", portion: 175, traits: [] },
      { name: "Bulgur", sv: "Bulgur", locked: true },
      { name: "Freekeh", sv: "Freekeh", locked: true },
      { name: "Teff", sv: "Teff", locked: true },
      { name: "Sorghum/Durra", sv: "Sorghum/durra", locked: true },
      { name: "Polenta", sv: "Polenta", locked: true },
      { name: "Millet", sv: "Hirs", locked: true },
      { name: "Tapioca", sv: "Tapioka", locked: true },
      { name: "Cornstarch", sv: "Majsstärkelse", locked: true },
      { name: "Gluten-free Oats", sv: "Glutenfri havre", locked: true },
      { name: "Spelt", sv: "Dinkel", locked: true },
      { name: "Semolina Porridge", sv: "Mannagrynsgröt", locked: true },
      { name: "Wheat Bran", sv: "Vetekli", locked: true },
      { name: "Rice Flour", sv: "Rismjöl", locked: true },
      { name: "Potato Flour", sv: "Potatismjöl", locked: true },
      { name: "Sugary Breakfast Cereal", sv: "Sötad frukostflingor", locked: true }
    ]
  },
  {
    id: "nuts",
    label: "Nuts & Seeds",
    sv: "Nötter och frön",
    foods: [
      { name: "Almond", sv: "Mandel", lmv: "Sötmandel", portion: 25, traits: ["over_10g_fat", "bile_stimulant", "fodmaps", "salicylate", "allergen_treenut", "cross_reactive"] },
      { name: "Brazil Nut", sv: "Paranöt", locked: true },
      { name: "Cashew Nut", sv: "Cashewnöt", locked: true },
      { name: "Chiaseeds (whole)", sv: "Chiafrön (hela)", locked: true },
      { name: "Chiaseeds (ground)", sv: "Chiafrön (malda)", locked: true },
      { name: "Flaxseed (whole)", sv: "Linfrön (hela)", locked: true },
      { name: "Psyllium Husk (whole)", sv: "Psylliumfrön (hela)", locked: true },
      { name: "Psyllium Husk (ground)", sv: "Psylliumfrön (malda)", locked: true },
      { name: "Flaxseed (ground)", sv: "Linfrön (malda)", locked: true },
      { name: "Hazelnut", sv: "Hasselnöt", locked: true },
      { name: "Peanut", sv: "Jordnöt", lmv: "Jordnötter torkade", portion: 25, traits: ["over_10g_fat", "bile_stimulant", "fodmaps", "allergen_peanut", "cross_reactive"] },
      { name: "Pumpkin Seeds", sv: "Pumpafrön", locked: true },
      { name: "Sunflower Seeds", sv: "Solrosfrön", locked: true },
      { name: "Walnut", sv: "Valnöt", lmv: "Valnötter", portion: 25, traits: ["over_10g_fat", "bile_stimulant", "allergen_treenut"] },
      { name: "Sesame Seeds", sv: "Sesamfrön", lmv: "Sesamfrö m. skal", portion: 5, traits: ["allergen_sesame"] },
      { name: "Macadamia", sv: "Macadamianöt", locked: true },
      { name: "Pecan", sv: "Pekannöt", locked: true },
      { name: "Chestnut", sv: "Kastanj", locked: true },
      { name: "Pistachio", sv: "Pistagenöt", locked: true },
      { name: "Pine Nuts", sv: "Pinjenötter", locked: true },
      { name: "Hemp Seeds", sv: "Hampafrön", locked: true },
      { name: "Poppy Seeds", sv: "Vallmofrön", locked: true },
      { name: "Sunflower Seed Butter", sv: "Solrosfröpasta", locked: true },
      { name: "Cocoa Beans", sv: "Kakaobönor", locked: true },
      { name: "Almond Flour", sv: "Mandelmjöl", locked: true },
      { name: "Peanut Butter", sv: "Jordnötssmör", locked: true }
    ]
  },
  {
    id: "legumes",
    label: "Legumes",
    sv: "Baljväxter",
    foods: [
      { name: "Black Bean", sv: "Svarta bönor", locked: true },
      { name: "Chickpea (whole/flour)", sv: "Kikärtor (hela/mjöl)", form: "cooked", lmv: "Kikärtor torkade kokta m. salt", portion: 150, traits: ["fiber", "fodmaps"] },
      { name: "Common Peas", sv: "Ärtor", locked: true },
      { name: "Lentils", sv: "Linser", form: "cooked", lmv: "Röda linser torkade kokta m. salt", lmvNote: "red lentils", portion: 150, traits: ["fiber", "protein", "fodmaps"] },
      { name: "Tempeh", sv: "Tempeh", locked: true },
      { name: "Tofu (firm)", sv: "Tofu (fast)", lmv: "Tofu fast", portion: 125, traits: ["allergen_soy", "cross_reactive", "dao_competitor"] },
      { name: "Tofu (silken)", sv: "Tofu (silke)", locked: true },
      { name: "Soybeans", sv: "Sojabönor", locked: true },
      { name: "Edamame", sv: "Edamame", locked: true },
      { name: "Falafel", sv: "Falafel", locked: true },
      { name: "Fava Beans", sv: "Bondbönor", locked: true },
      { name: "Kidney Beans", sv: "Kidneybönor", locked: true },
      { name: "Pinto Beans", sv: "Pintobönor", locked: true },
      { name: "Split Peas", sv: "Spritärtor", locked: true },
      { name: "White Beans in Tomato Sauce", sv: "Vita bönor i tomatsås", locked: true },
      { name: "Green Lentils", sv: "Gröna linser", locked: true },
      { name: "Mung Beans", sv: "Mungbönor", locked: true },
      { name: "Adzuki Beans", sv: "Adzukibönor", locked: true },
      { name: "Butter Beans", sv: "Smörbönor", locked: true },
      { name: "Mung Bean Sprouts", sv: "Mungbönsgroddar", locked: true },
      { name: "Adzuki Bean Sprouts", sv: "Adzukigroddar", locked: true },
      { name: "Lentil Sprouts", sv: "Linsgroddar", locked: true },
      { name: "Alfalfa Sprouts", sv: "Alfalfagroddar", locked: true },
      { name: "White Beans (cooked)", sv: "Vita bönor (kokta)", locked: true }
    ]
  },
  {
    id: "bread",
    label: "Bread, Pasta & Noodles",
    sv: "Bröd, pasta och nudlar",
    foods: [
      { name: "Rye Bread (whole grain)", sv: "Rågbröd (fullkorn)", lmv: "Bröd fullkorn råg fibrer ca 7%", portion: 40, traits: ["fodmaps", "allergen_wheat"] },
      { name: "Couscous", sv: "Couscous", locked: true },
      { name: "Pita Bread", sv: "Pitabröd", locked: true },
      { name: "Naan Bread", sv: "Naanbröd", locked: true },
      { name: "Soba Noodles", sv: "Sobanudlar", locked: true },
      { name: "Rice Noodles", sv: "Risnudlar", locked: true },
      { name: "White Bread", sv: "Vitt bröd", lmv: "Bröd vitt fibrer 3,5%", portion: 40, traits: ["allergen_wheat", "fodmaps", "refined_carbs"] },
      { name: "Pasta (no egg)", sv: "Pasta (utan ägg)", form: "cooked", lmv: "Pasta kokt u. salt", portion: 175, traits: ["refined_carbs", "allergen_wheat", "fodmaps"] },
      { name: "Crispbread (rye)", sv: "Knäckebröd (råg)", locked: true },
      { name: "Rice Cakes", sv: "Riskakor", locked: true },
      { name: "Sourdough Bread (wheat)", sv: "Surdegsbröd (vete)", locked: true },
      { name: "Gluten-free Bread", sv: "Glutenfritt bröd", locked: true },
      { name: "Gluten-free Crispbread", sv: "Glutenfritt knäckebröd", locked: true },
      { name: "Gluten-free Pasta", sv: "Glutenfri pasta", locked: true },
      { name: "Corn Tortilla", sv: "Majstortilla", locked: true },
      { name: "Rusks (whole grain)", sv: "Skorpor (fullkorn)", locked: true },
      { name: "Fresh Pasta (w/ egg)", sv: "Färsk pasta (med ägg)", locked: true }
    ]
  },
  {
    id: "cheese",
    label: "Cheese",
    sv: "Ost",
    foods: [
      { name: "Cream Cheese (<10% fat)", sv: "Färskost (<10 % fett)", lmv: "Färskost cream cheese extra light fett 5%", portion: 20, traits: ["allergen_milk"] },
      { name: "Cream Cheese (>10% fat)", sv: "Färskost (>10 % fett)", locked: true },
      { name: "Hard Cheese (~15% fat)", sv: "Hårdost (~15 % fett)", locked: true },
      { name: "Hard Cheese (~28-35% fat)", sv: "Hårdost (~28–35 % fett)", lmv: "Ost hårdost fett 31%", portion: 20, traits: ["over_10g_fat", "histamine", "dao_competitor", "allergen_milk"] },
      { name: "Cottage Cheese (4% fat)", sv: "Cottage cheese (4 % fett)", locked: true },
      { name: "Ricotta Cheese", sv: "Ricotta", locked: true },
      { name: "Mascarpone", sv: "Mascarpone", locked: true },
      { name: "Parmesan", sv: "Parmesan", lmv: "Ost hårdost parmesan fett 30% typ Parmiggiano Reggiano", portion: 20, traits: ["over_10g_fat", "histamine", "dao_competitor", "allergen_milk"] },
      { name: "Halloumi", sv: "Halloumi", locked: true },
      { name: "Mozzarella", sv: "Mozzarella", locked: true },
      { name: "Blue Cheese", sv: "Ädelost", lmv: "Ädelost grönmögelost fett 17%", portion: 20, traits: ["histamine", "dao_competitor", "allergen_milk"] },
      { name: "Roquefort", sv: "Roquefort", locked: true },
      { name: "Fontina", sv: "Fontina", locked: true },
      { name: "Raclette", sv: "Raclette", locked: true },
      { name: "Camembert", sv: "Camembert", locked: true },
      { name: "Cheddar", sv: "Cheddar", locked: true },
      { name: "Aged Gouda", sv: "Lagrad gouda", locked: true },
      { name: "Feta Cheese", sv: "Fetaost", locked: true },
      { name: "Paneer", sv: "Paneer", locked: true },
      { name: "Brie", sv: "Brie", locked: true },
      { name: "Emmental", sv: "Emmentaler", locked: true },
      { name: "Lactose-free Cheese", sv: "Laktosfri ost", locked: true },
      { name: "Beaufort", sv: "Beaufort", locked: true },
      { name: "Maasdam", sv: "Maasdam", locked: true },
      { name: "Fourme d'Ambert", sv: "Fourme d'Ambert", locked: true },
      { name: "Gorgonzola", sv: "Gorgonzola", locked: true },
      { name: "Gruyere", sv: "Gruyère", locked: true },
      { name: "Pecorino", sv: "Pecorino", locked: true },
      { name: "Provolone", sv: "Provolone", locked: true },
      { name: "Pelardon (goat cheese)", sv: "Pélardon (getost)", locked: true },
      { name: "Reblochon", sv: "Reblochon", locked: true },
      { name: "Salers", sv: "Salers", locked: true },
      { name: "Tomme", sv: "Tomme", locked: true }
    ]
  },
  {
    id: "seafood",
    label: "Fish & Shellfish",
    sv: "Fisk och skaldjur",
    foods: [
      { name: "Salmon", sv: "Lax", lmv: "Lax stekt m. salt", portion: 125, traits: ["over_10g_fat", "bile_stimulant", "protein", "allergen_fish", "histamine", "dao_competitor"] },
      { name: "Cod", sv: "Torsk", lmv: "Torsk rå", portion: 125, traits: ["protein", "histamine", "allergen_fish"] },
      { name: "Oysters", sv: "Ostron", locked: true },
      { name: "Lobsters", sv: "Hummer", locked: true },
      { name: "Crayfish", sv: "Kräfta", locked: true },
      { name: "Shrimp", sv: "Räka", lmv: "Räka kokt", portion: 80, traits: ["allergen_crustacean", "histamine"] },
      { name: "Tuna", sv: "Tonfisk", locked: true },
      { name: "Anchovies", sv: "Ansjovis", locked: true },
      { name: "Smoked Salmon", sv: "Rökt lax", locked: true },
      { name: "Crab", sv: "Krabba", locked: true },
      { name: "Mussels", sv: "Musslor", lmv: "Mussla konserv. m. lag", portion: 80, traits: ["allergen_mollusc", "histamine"] },
      { name: "Fish Balls", sv: "Fiskbullar", locked: true },
      { name: "Fish Fingers", sv: "Fiskpinnar", locked: true },
      { name: "Mackerel", sv: "Makrill", locked: true },
      { name: "Sardines (canned)", sv: "Sardiner (konserv)", locked: true },
      { name: "Pickled Herring", sv: "Inlagd sill", locked: true },
      { name: "Surimi / Crab Sticks", sv: "Surimi / krabbstickor", locked: true },
      { name: "Squid", sv: "Bläckfisk", locked: true },
      { name: "Cod Liver (canned)", sv: "Torsklever (konserv)", locked: true },
      { name: "Perch", sv: "Abborre", locked: true },
      { name: "Pike", sv: "Gädda", locked: true },
      { name: "Haddock", sv: "Kolja", locked: true },
      { name: "Turbot", sv: "Piggvar", locked: true },
      { name: "Whitefish", sv: "Sik", locked: true },
      { name: "Smoked Herring", sv: "Böckling", locked: true },
      { name: "Fish Roe", sv: "Fiskrom", locked: true }
    ]
  },
  {
    id: "meat",
    label: "Meat, Poultry & Eggs",
    sv: "Kött, fågel och ägg",
    foods: [
      { name: "Cows Meat", sv: "Nötkött", lmv: "Nöt kött rå", portion: 125, traits: ["bile_stimulant", "protein", "alpha_gal"] },
      { name: "Pork (lean cut)", sv: "Fläskkött (magert)", locked: true },
      { name: "Pork (fatty cut)", sv: "Fläskkött (fett)", locked: true },
      { name: "Elk Meat", sv: "Älgkött", locked: true },
      { name: "Chicken", sv: "Kyckling", lmv: "Kyckling kokt m. salt", portion: 125, traits: ["bile_stimulant", "protein"] },
      { name: "Egg White", sv: "Äggvita", locked: true },
      { name: "Egg Yolk", sv: "Äggula", locked: true },
      { name: "Whole Egg", sv: "Helt ägg", lmv: "Ägg rått", portion: 50, traits: ["allergen_egg"] },
      { name: "Minced Meat (~10% fat)", sv: "Köttfärs (~10 % fett)", locked: true },
      { name: "Minced Meat (~15% fat)", sv: "Köttfärs (~15 % fett)", locked: true },
      { name: "Minced Meat (~20% fat)", sv: "Köttfärs (~20 % fett)", locked: true },
      { name: "Lamb", sv: "Lamm", locked: true },
      { name: "Duck (with skin)", sv: "Anka (med skinn)", locked: true },
      { name: "Turkey", sv: "Kalkon", locked: true },
      { name: "Reindeer", sv: "Renkött", locked: true },
      { name: "Goat Meat", sv: "Getkött", locked: true },
      { name: "Ostrich", sv: "Struts", locked: true },
      { name: "Quail", sv: "Vaktel", locked: true },
      { name: "Rabbit", sv: "Kanin", locked: true },
      { name: "Pheasant", sv: "Fasan", locked: true },
      { name: "Ptarmigan", sv: "Ripa", locked: true },
      { name: "Hare", sv: "Hare", locked: true },
      { name: "Roe Deer", sv: "Rådjur", locked: true }
    ]
  },
  {
    id: "milkFermented",
    label: "Milk & Fermented Dairy",
    sv: "Mjölk och syrade produkter",
    foods: [
      { name: "Cows Milk (3% fat)", sv: "Komjölk (3 % fett)", lmv: "Mjölk fett 3% berikad", portion: 200, traits: ["over_3g_lactose", "fodmaps", "allergen_milk"] },
      { name: "Goats Milk", sv: "Getmjölk", locked: true },
      { name: "Sheeps Milk", sv: "Fårmjölk", locked: true },
      { name: "Yogurt (0.5% fat)", sv: "Yoghurt (0,5 % fett)", locked: true },
      { name: "Yogurt (3% fat)", sv: "Yoghurt (3 % fett)", lmv: "Yoghurt naturell fett 3% berikad", portion: 200, traits: ["over_3g_lactose", "fodmaps", "allergen_milk"] },
      { name: "Greek Yogurt (10% fat)", sv: "Grekisk yoghurt (10 % fett)", locked: true },
      { name: "Cream (40% fat)", sv: "Grädde (40 % fett)", lmv: "Vispgrädde fett 40%", portion: 25, traits: ["over_10g_fat", "bile_stimulant", "allergen_milk"] },
      { name: "Quark (~1%)", sv: "Kvarg (~1 %)", locked: true },
      { name: "Quark (~10%)", sv: "Kvarg (~10 %)", locked: true },
      { name: "Sour Cream (12% fat)", sv: "Gräddfil (12 % fett)", locked: true },
      { name: "Whey Protein", sv: "Vassleprotein", locked: true },
      { name: "Skyr", sv: "Skyr", locked: true },
      { name: "Buttermilk", sv: "Kärnmjölk", locked: true },
      { name: "Kefir", sv: "Kefir", locked: true },
      { name: "Lactose-free Milk", sv: "Laktosfri mjölk", locked: true },
      { name: "Lactose-free Yogurt", sv: "Laktosfri yoghurt", locked: true },
      { name: "Filmjolk", sv: "Filmjölk", locked: true },
      { name: "Creme Fraiche (34% fat)", sv: "Crème fraiche (34 % fett)", locked: true },
      { name: "Lactose-free Cream (40% fat)", sv: "Laktosfri grädde (40 % fett)", locked: true },
      { name: "Flavored Yogurt", sv: "Smaksatt yoghurt", locked: true }
    ]
  },
  {
    id: "offal",
    label: "Offal",
    sv: "Inälvsmat",
    foods: [
      { name: "Beef Liver", sv: "Nötlever", lmv: "Nöt lever rå", portion: 125, traits: ["protein", "alpha_gal"] },
      { name: "Liver Pate", sv: "Leverpastej", lmv: "Leverpastej bredbar fett ca 24%", lmvNote: "the spreadable kind, 24 % fat", portion: 20, traits: ["alpha_gal"] },
      { name: "Blood Pudding", sv: "Blodpudding", lmv: "Blodpudding blodkorv fett 14%", portion: 125, traits: ["over_10g_fat", "bile_stimulant", "fodmaps", "allergen_wheat", "alpha_gal"] },
      { name: "Foie Gras", sv: "Foie gras", locked: true },
      { name: "Liver Sausage", sv: "Leverkorv", locked: true },
      { name: "Chicken Liver", sv: "Kycklinglever", locked: true },
      { name: "Turkey Liver", sv: "Kalkonlever", locked: true },
      { name: "Turkey Heart", sv: "Kalkonhjärta", locked: true },
      { name: "Beef Kidney", sv: "Nötnjure", locked: true },
      { name: "Lamb Kidney", sv: "Lammnjure", locked: true },
      { name: "Veal Kidney", sv: "Kalvnjure", locked: true },
      { name: "Offal (mixed, cooked)", sv: "Inälvsmat (blandad, kokt)", locked: true },
      { name: "Lamb Liver", sv: "Lammlever", locked: true },
      { name: "Reindeer Liver", sv: "Renlever", locked: true }
    ]
  },
  {
    id: "charcuterie",
    label: "Charcuterie & Sausage",
    sv: "Chark och korv",
    foods: [
      { name: "Salami", sv: "Salami", lmv: "Påläggskorv salami rökt", portion: 20, traits: ["over_10g_fat", "histamine", "dao_competitor", "alpha_gal"] },
      { name: "Dry-Cured Ham (~12%)", sv: "Lufttorkad skinka (~12 %)", locked: true },
      { name: "Chicken Sausage", sv: "Kycklingkorv", locked: true },
      { name: "Breakfast Sausage (fried)", sv: "Frukostkorv (stekt)", locked: true },
      { name: "Frozen Meatballs", sv: "Frysta köttbullar", locked: true },
      { name: "Hot Dog Sausage", sv: "Varmkorv", lmv: "Korv varmkorv kokt", portion: 100, traits: ["over_10g_fat", "bile_stimulant", "histamine", "alpha_gal"] },
      { name: "Chicken Nuggets", sv: "Kycklingnuggets", locked: true },
      { name: "Bacon", sv: "Bacon", lmv: "Gris bacon stekt", portion: 20, traits: ["over_10g_fat", "histamine", "dao_competitor", "alpha_gal"] },
      { name: "Dried Reindeer Meat", sv: "Torkat renkött", locked: true },
      { name: "Horse Meat (smoked)", sv: "Hästkött (rökt)", locked: true },
      { name: "Kassler", sv: "Kassler", locked: true },
      { name: "Smoked Ham (~6% fat)", sv: "Rökt skinka (~6 % fett)", locked: true }
    ]
  },
  {
    id: "spices",
    label: "Spices & Herbs",
    sv: "Kryddor och örter",
    foods: [
      { name: "Chili (fresh)", sv: "Chili (färsk)", bothWays: true, form: "fresh", lmv: "Chilipeppar färsk", portion: 5, traits: ["irritant"] },
      { name: "Garlic", sv: "Vitlök", form: "fresh", lmv: "Vitlök", portion: 5, traits: ["fodmaps", "irritant", "allergen_onion"] },
      { name: "Garlic Powder", sv: "Vitlökspulver", locked: true },
      { name: "Ginger (fresh)", sv: "Ingefära (färsk)", locked: true },
      { name: "Ginger (dried)", sv: "Ingefära (torkad)", locked: true },
      { name: "Dill (fresh)", sv: "Dill (färsk)", locked: true },
      { name: "Dill (dried)", sv: "Dill (torkad)", locked: true },
      { name: "Turmeric (dried)", sv: "Gurkmeja (torkad)", locked: true },
      { name: "Mustard", sv: "Senap", lmv: "Senap svensk", portion: 5, traits: ["irritant", "allergen_mustard", "cross_reactive"] },
      { name: "Black Pepper", sv: "Svartpeppar", form: "dried", portion: 2, traits: ["irritant", "cross_reactive"] },
      { name: "Sumac", sv: "Sumak", locked: true },
      { name: "Cumin (dried)", sv: "Spiskummin (torkad)", locked: true },
      { name: "Wasabi", sv: "Wasabi", locked: true },
      { name: "Curry Powder", sv: "Currypulver", locked: true },
      { name: "Sichuan Peppercorn", sv: "Sichuanpeppar", locked: true },
      { name: "Nutmeg", sv: "Muskotnöt", locked: true },
      { name: "Basil (fresh)", sv: "Basilika (färsk)", locked: true },
      { name: "Basil (dried)", sv: "Basilika (torkad)", locked: true },
      { name: "Oregano (dried)", sv: "Oregano (torkad)", locked: true },
      { name: "Thyme (dried)", sv: "Timjan (torkad)", locked: true },
      { name: "Thyme (fresh)", sv: "Timjan (färsk)", locked: true },
      { name: "Rosemary (dried)", sv: "Rosmarin (torkad)", locked: true },
      { name: "Rosemary (fresh)", sv: "Rosmarin (färsk)", locked: true },
      { name: "Mint (fresh)", sv: "Mynta (färsk)", locked: true },
      { name: "Mint (dried)", sv: "Mynta (torkad)", locked: true },
      { name: "Cinnamon", sv: "Kanel", locked: true },
      { name: "Paprika Powder", sv: "Paprikapulver", locked: true },
      { name: "Cardamom (dried)", sv: "Kardemumma (torkad)", locked: true },
      { name: "Allspice", sv: "Kryddpeppar", locked: true },
      { name: "Onion Powder", sv: "Lökpulver", locked: true }
    ]
  },
  {
    id: "condiments",
    label: "Condiments",
    sv: "Smaksättare",
    foods: [
      { name: "Salt", sv: "Salt", lmv: "Salt m. jod", portion: 5, traits: [] },
      { name: "Vinegar", sv: "Ättika", portion: 5, traits: ["irritant"] },
      { name: "Balsamic Vinegar", sv: "Balsamvinäger", locked: true },
      { name: "Soy Sauce", sv: "Soja", lmv: "Sojasås", portion: 5, traits: ["histamine", "allergen_soy", "allergen_wheat", "dao_competitor"] },
      { name: "Fish Sauce", sv: "Fisksås", locked: true },
      { name: "Teriyaki Sauce", sv: "Teriyakisås", locked: true },
      { name: "Hot Sauce", sv: "Hetsås", locked: true },
      { name: "Harissa", sv: "Harissa", locked: true },
      { name: "Tamarind", sv: "Tamarind", locked: true },
      { name: "Preserved Lemon", sv: "Saltkonserverad citron", locked: true },
      { name: "Pesto", sv: "Pesto", locked: true },
      { name: "Yeast Extract (Marmite type)", sv: "Jästextrakt (Marmite-typ)", locked: true },
      { name: "Nutritional Yeast", sv: "Näringsjäst", locked: true }
    ]
  },
  {
    id: "sauces",
    label: "Sauces & Dressings",
    sv: "Såser och dressingar",
    foods: [
      { name: "Ketchup", sv: "Ketchup", lmv: "Ketchup", portion: 25, traits: ["irritant", "dao_competitor"] },
      { name: "Mayonnaise", sv: "Majonnäs", lmv: "Majonnäs fett 80%", portion: 25, traits: ["over_10g_fat", "bile_stimulant", "allergen_egg"] },
      { name: "Vegan Mayonnaise", sv: "Vegansk majonnäs", locked: true },
      { name: "Aioli", sv: "Aioli", locked: true },
      { name: "Remoulade", sv: "Remoulad", locked: true },
      { name: "Tartar Sauce", sv: "Tartarsås", locked: true },
      { name: "Ranch Dressing", sv: "Ranchdressing", locked: true },
      { name: "Thousand Island Dressing", sv: "Rhode Island-dressing", locked: true },
      { name: "Tzatziki", sv: "Tzatziki", locked: true },
      { name: "Barbecue Sauce", sv: "Barbecuesås", locked: true },
      { name: "Horseradish Sauce", sv: "Pepparrotssås", locked: true },
      { name: "Salsa", sv: "Salsa", locked: true },
      { name: "Satay / Peanut Sauce", sv: "Satay- / jordnötssås", locked: true },
      { name: "Béarnaise Sauce", sv: "Bearnaisesås", locked: true },
      { name: "Hollandaise Sauce", sv: "Hollandaisesås", locked: true },
      { name: "Bechamel Sauce", sv: "Bechamelsås", lmv: "Béchamelsås", portion: 60, traits: ["allergen_milk", "allergen_wheat"] },
      { name: "Tomato Pasta Sauce", sv: "Tomatsås till pasta", locked: true }
    ]
  },
  {
    id: "dips",
    label: "Dips & Spreads",
    sv: "Röror",
    foods: [
      { name: "Hummus", sv: "Hummus", lmv: "Hummus kikärtsröra", portion: 50, traits: ["over_10g_fat", "bile_stimulant", "fodmaps", "allergen_sesame"] },
      { name: "Guacamole", sv: "Guacamole", lmv: "Guacamole", portion: 50, traits: ["over_10g_fat", "cross_reactive"] },
      { name: "Baba Ganoush", sv: "Baba ganoush", locked: true },
      { name: "Tahini", sv: "Tahini", lmv: "Tahini", portion: 25, traits: ["over_10g_fat", "bile_stimulant", "allergen_sesame"] },
      { name: "Ajvar", sv: "Ajvar", locked: true },
      { name: "Mango Chutney", sv: "Mangochutney", locked: true },
      { name: "Cranberry Sauce", sv: "Tranbärssås", locked: true },
      { name: "Fish Roe Spread", sv: "Kaviar (pålägg)", locked: true }
    ]
  },
  {
    id: "sweetSpreads",
    label: "Sweet Spreads",
    sv: "Söta pålägg",
    foods: [
      { name: "Chocolate Spread (hazelnut)", sv: "Chokladpålägg (hasselnöt)", portion: 20, traits: ["over_10g_fat", "refined_carbs", "allergen_milk", "allergen_treenut"] },
      { name: "Dulce de Leche", sv: "Dulce de leche", locked: true },
      { name: "Apricot Jam", sv: "Aprikossylt", locked: true },
      { name: "Blueberry Jam", sv: "Blåbärssylt", locked: true },
      { name: "Cherry Jam", sv: "Körsbärssylt", locked: true },
      { name: "Fig Jam", sv: "Fikonsylt", locked: true },
      { name: "Plum Jam", sv: "Plommonsylt", locked: true },
      { name: "Raspberry Jam", sv: "Hallonsylt", locked: true },
      { name: "Strawberry Jam", sv: "Jordgubbssylt", portion: 20, traits: ["refined_carbs", "cross_reactive"] },
      { name: "Strawberry Jam (reduced sugar)", sv: "Jordgubbssylt (sockerreducerad)", locked: true },
      { name: "Blackberry Jelly", sv: "Björnbärsgelé", locked: true },
      { name: "Redcurrant Jelly", sv: "Rödvinbärsgelé", locked: true },
      { name: "Orange Marmalade", sv: "Apelsinmarmelad", portion: 20, traits: ["refined_carbs", "cross_reactive"] }
    ]
  },
  {
    id: "picklesFerments",
    label: "Pickles & Ferments",
    sv: "Inlagt och fermenterat",
    foods: [
      { name: "Kimchi", sv: "Kimchi", locked: true },
      { name: "Sauerkraut", sv: "Surkål", lmv: "Surkål konserv. m. lag", portion: 50, traits: ["histamine", "dao_competitor"] },
      { name: "Pickled Cucumber", sv: "Inlagd gurka", lmv: "Gurka inlagd", portion: 25, traits: ["histamine", "irritant"] },
      { name: "Olives", sv: "Oliver", lmv: "Oliver gröna m. paprikafyllning avrunna", portion: 25, traits: ["histamine"] },
      { name: "Miso Paste", sv: "Misopasta", locked: true },
      { name: "Pickled Beetroot", sv: "Inlagd rödbeta", locked: true },
      { name: "Pickled Onion", sv: "Inlagd lök", locked: true },
      { name: "Pickled Jalapeno", sv: "Inlagd jalapeño", locked: true },
      { name: "Pickled Ginger", sv: "Inlagd ingefära", locked: true },
      { name: "Salt-brined Pickles", sv: "Saltlakegurka", locked: true },
      { name: "Capers", sv: "Kapris", locked: true },
      { name: "Natto", sv: "Natto", locked: true }
    ]
  },
  {
    id: "fats",
    label: "Fats & Oils",
    sv: "Fetter och oljor",
    foods: [
      { name: "Butter", sv: "Smör", lmv: "Smör fett 80%", portion: 10, traits: ["over_10g_fat", "allergen_milk"] },
      { name: "Margarine", sv: "Margarin", lmv: "Flytande margarin fett 70%", portion: 10, traits: ["over_10g_fat"] },
      { name: "Sesame Oil", sv: "Sesamolja", locked: true },
      { name: "Olive Oil", sv: "Olivolja", lmv: "Olivolja", portion: 10, traits: ["over_10g_fat", "bile_stimulant"] },
      { name: "Sunflower Oil", sv: "Solrosolja", locked: true },
      { name: "Rapeseed Oil", sv: "Rapsolja", locked: true },
      { name: "Coconut Oil", sv: "Kokosolja", locked: true },
      { name: "Ghee", sv: "Ghee", locked: true },
      { name: "Garlic-infused Oil", sv: "Vitlöksolja", locked: true },
      { name: "Cod Liver Oil", sv: "Torskleverolja", locked: true }
    ]
  },
  {
    id: "sweeteners",
    label: "Sweeteners",
    sv: "Sötningsmedel",
    foods: [
      { name: "Honey", sv: "Honung", lmv: "Honung", portion: 25, traits: ["fodmaps"] },
      { name: "White Sugar", sv: "Vitt socker", lmv: "Socker", portion: 5, traits: ["refined_carbs"] },
      { name: "Maple Syrup", sv: "Lönnsirap", portion: 25, sugarsOfCarbs: 0.9, traits: ["refined_carbs"] },
      { name: "Agave Syrup", sv: "Agavesirap", locked: true }
    ]
  },
  {
    id: "confectionery",
    label: "Confectionery",
    sv: "Konfektyr",
    foods: [
      { name: "Candy bars", sv: "Chokladbitar", locked: true },
      { name: "Milk chocolate", sv: "Mjölkchoklad", lmv: "Mjölkchoklad", portion: 30, traits: ["irritant", "over_10g_fat", "bile_stimulant", "refined_carbs", "over_3g_lactose", "fodmaps", "caffeine", "allergen_milk"] },
      { name: "Dark Chocolate", sv: "Mörk choklad", lmv: "Mörk choklad kakao ≥ 70%", portion: 25, traits: ["irritant", "over_10g_fat", "bile_stimulant", "refined_carbs", "caffeine"] },
      { name: "Halva", sv: "Halva", locked: true },
      { name: "Sugar-free Chewing Gum", sv: "Sockerfritt tuggummi", locked: true },
      { name: "Marzipan", sv: "Marsipan", locked: true },
      { name: "Liquorice", sv: "Lakrits", lmv: "Lakritsgodis", portion: 30, traits: ["refined_carbs"] },
      { name: "Salty Liquorice", sv: "Saltlakrits", locked: true },
      { name: "Candied Chestnut", sv: "Kanderad kastanj", locked: true },
      { name: "Candied Fruit", sv: "Kanderad frukt", locked: true },
      { name: "Candied Orange Peel", sv: "Kanderat apelsinskal", locked: true },
      { name: "Chewy Caramel", sv: "Kola", locked: true },
      { name: "Hard Candy", sv: "Hårt godis", locked: true },
      { name: "Caramel Hard Candy", sv: "Karamell", locked: true },
      { name: "Marshmallow", sv: "Marshmallow", locked: true },
      { name: "Meringue", sv: "Maräng", locked: true },
      { name: "Sugared Almond", sv: "Dragerad mandel", locked: true },
      { name: "Nougat Chocolate Bar", sv: "Chokladbar med nougat", locked: true },
      { name: "Coconut Chocolate Bar", sv: "Chokladbar med kokos", locked: true },
      { name: "Chocolate Bar with Dried Fruit", sv: "Chokladbar med torkad frukt", locked: true },
      { name: "Dark Chocolate with Nuts", sv: "Mörk choklad med nötter", locked: true },
      { name: "Dark Chocolate with Praline", sv: "Mörk choklad med praliné", locked: true },
      { name: "Mint Chocolate", sv: "Mintchoklad", locked: true },
      { name: "Milk Chocolate with Praline", sv: "Mjölkchoklad med praliné", locked: true },
      { name: "White Chocolate with Nuts", sv: "Vit choklad med nötter", locked: true }
    ]
  },
  {
    id: "softDrinks",
    label: "Soft Drinks, Coffee & Tea",
    sv: "Läsk, kaffe och te",
    foods: [
      { name: "Schilcherwein", sv: "Schilcherwein", locked: true },
      { name: "Coffee", sv: "Kaffe", lmv: "Kaffe bryggt", portion: 200, traits: ["caffeine", "irritant"] },
      { name: "Espresso", sv: "Espresso", locked: true },
      { name: "Black Tea", sv: "Svart te", portion: 200, traits: ["caffeine", "irritant"] },
      { name: "Green Tea", sv: "Grönt te", locked: true },
      { name: "Mate Tea", sv: "Mate-te", locked: true },
      { name: "Energy Drinks", sv: "Energidryck", locked: true },
      { name: "Matcha", sv: "Matcha", locked: true },
      { name: "Chai Tea", sv: "Chai-te", locked: true },
      { name: "Chamomile Tea", sv: "Kamomillte", locked: true },
      { name: "Kombucha", sv: "Kombucha", locked: true },
      { name: "Orange Juice", sv: "Apelsinjuice", locked: true },
      { name: "Apple Juice", sv: "Äppeljuice", locked: true },
      { name: "Peppermint Tea", sv: "Pepparmyntste", locked: true },
      { name: "Squash / Cordial", sv: "Saft", locked: true },
      { name: "Hot Chocolate", sv: "Varm choklad", locked: true },
      { name: "Sugary soft drinks", sv: "Sockrad läsk", locked: true },
      { name: "Cola", sv: "Cola", lmv: "Läsk cola", portion: 330, traits: ["caffeine", "refined_carbs", "irritant"] }
    ]
  },
  {
    id: "bakedDesserts",
    label: "Biscuits, Cakes & Desserts",
    sv: "Kex, bakverk och desserter",
    foods: [
      { name: "Rosehip Soup", sv: "Nyponsoppa", locked: true },
      { name: "Granola Bar", sv: "Müslibar", locked: true },
      { name: "Protein Bar", sv: "Proteinbar", locked: true },
      { name: "Ice Cream", sv: "Glass", lmv: "Glass fett ca 10%", portion: 100, traits: ["over_10g_fat", "bile_stimulant", "refined_carbs", "over_3g_lactose", "fodmaps", "allergen_milk"] },
      { name: "Baklava", sv: "Baklava", locked: true },
      { name: "Cinnamon Bun", sv: "Kanelbulle", lmv: "Sött vetebröd kanelbulle gräddad kylvara frysvara el. butiksbakad", lmvNote: "the 18.5 g of sugar is nearly all sucrose — the milk in the dough leaves well under a gram of lactose", portion: 60, traits: ["over_10g_fat", "refined_carbs", "fodmaps", "allergen_milk", "allergen_wheat"] },
      { name: "Sponge Fingers", sv: "Savoiardikex", locked: true },
      { name: "Almond Thins", sv: "Mandelflarn", locked: true },
      { name: "Biscuit (reduced fat)", sv: "Kex (fettreducerat)", locked: true },
      { name: "Chocolate Chip Biscuit", sv: "Chokladkaka (kex)", locked: true },
      { name: "Wafer Biscuit", sv: "Rån", locked: true },
      { name: "Filled Wafer Biscuit", sv: "Fyllt rån", locked: true },
      { name: "Ice Cream Cone", sv: "Glasstrut", locked: true },
      { name: "Panna Cotta", sv: "Panna cotta", locked: true },
      { name: "Digestive Biscuit", sv: "Digestivekex", lmv: "Kex digestive fullkorn 23%", portion: 30, traits: ["refined_carbs", "allergen_wheat"] },
      { name: "Spettekaka", sv: "Spettekaka", locked: true },
      { name: "Sorbet", sv: "Sorbet", locked: true },
      { name: "Tiramisu", sv: "Tiramisu", locked: true }
    ]
  },
  {
    id: "alcohol",
    label: "Alcoholic Drinks",
    sv: "Alkoholhaltiga drycker",
    foods: [
      { name: "Red Wine", sv: "Rödvin", lmv: "Vin rött vol. % 14", portion: 150, traits: ["alcohol", "histamine", "irritant", "allergen_sulphite"] },
      { name: "White Wine", sv: "Vitt vin", locked: true },
      { name: "Champagne", sv: "Champagne", locked: true },
      { name: "Beer", sv: "Öl", lmv: "Öl starköl el. exportöl vol. % 5,4", portion: 330, traits: ["alcohol", "histamine", "irritant", "allergen_wheat"] },
      { name: "Cider", sv: "Cider", locked: true },
      { name: "Spirits (Liquor)", sv: "Sprit", lmv: "Whisky vol. % 40", portion: 40, traits: ["alcohol", "irritant", "histamine"] },
      { name: "Alcohol-free Beer", sv: "Alkoholfri öl", locked: true },
      { name: "Low-alcohol Beer", sv: "Lättöl", locked: true },
      { name: "Shandy", sv: "Shandy", locked: true },
      { name: "Rose Wine", sv: "Rosévin", locked: true },
      { name: "Sweet Wine", sv: "Sött vin", locked: true },
      { name: "Sangria", sv: "Sangria", locked: true },
      { name: "Sake", sv: "Sake", locked: true },
      { name: "Liqueur", sv: "Likör", locked: true },
      { name: "Glögg", sv: "Glögg", locked: true },
      { name: "Punsch", sv: "Punsch", locked: true }
    ]
  },
  {
    id: "plantBased",
    label: "Plant-Based Substitutes",
    sv: "Växtbaserade alternativ",
    foods: [
      { name: "Seitan", sv: "Seitan", locked: true },
      { name: "Soy Milk", sv: "Sojadryck", lmv: "Sojadryck", portion: 200, traits: ["allergen_soy", "fodmaps", "dao_competitor"] },
      { name: "Oat Drink", sv: "Havredryck", lmv: "Havredryck fett 1,5% berikad", portion: 200, traits: ["allergen_wheat"] },
      { name: "Coconut Milk", sv: "Kokosmjölk", locked: true },
      { name: "Almond Milk", sv: "Mandeldryck", locked: true },
      { name: "Soy Yogurt", sv: "Sojayoghurt", locked: true },
      { name: "Oat Yogurt", sv: "Havreyoghurt", locked: true },
      { name: "Oat Fraiche", sv: "Havrefraiche", locked: true },
      { name: "Vegan Cheese (Coconut Oil)", sv: "Vegansk ost (kokosolja)", locked: true },
      { name: "Vegan Cheese (Cashew)", sv: "Vegansk ost (cashew)", locked: true },
      { name: "Plant-based Mince", sv: "Växtbaserad färs", locked: true },
      { name: "Quorn", sv: "Quorn", lmv: "Mykoprotein bullar frysvara", lmvNote: "mycoprotein balls — plain pieces are not listed", portion: 125, traits: ["protein", "allergen_egg", "allergen_mushroom"] },
      { name: "Veggie Burger (vegetable-based)", sv: "Vegoburgare (grönsaksbaserad)", locked: true },
      { name: "Aquafaba", sv: "Aquafaba", locked: true }
    ]
  },
  {
    id: "savourySnacks",
    label: "Savoury Snacks",
    sv: "Salta snacks",
    foods: [
      { name: "Pretzels", sv: "Saltkringlor", locked: true },
      { name: "Potato chips", sv: "Potatischips", lmv: "Chips potatis naturell", portion: 30, traits: ["over_10g_fat"] },
      { name: "Cheese Puffs / Snacks", sv: "Ostbågar", locked: true },
      { name: "Microwave Popcorn", sv: "Mikropopcorn", locked: true },
      { name: "Savoury Crackers", sv: "Salta kex", lmv: "Kex salta", portion: 20, traits: ["refined_carbs", "allergen_wheat"] },
      { name: "Sesame Crackers", sv: "Sesamkex", locked: true },
      { name: "Potato chips (light, ~25% fat)", sv: "Potatischips (light, ~25 % fett)", locked: true },
      { name: "Potato chips (flavoured)", sv: "Potatischips (smaksatta)", locked: true },
      { name: "Tortilla Chips", sv: "Tortillachips", locked: true },
      { name: "Peanut Puffs", sv: "Jordnötsbågar", locked: true },
      { name: "Corn Puffs (toddler snack)", sv: "Majskrokar (barnsnacks)", locked: true },
      { name: "Chilli Nuts", sv: "Chilinötter", locked: true },
      { name: "Lentil Puffs", sv: "Linsbågar", locked: true },
      { name: "Roasted Chickpeas", sv: "Rostade kikärtor", locked: true },
      { name: "Japanese Rice Cracker Mix", sv: "Japanmix", locked: true },
      { name: "Salted Roasted Peanuts", sv: "Saltade rostade jordnötter", lmv: "Jordnötter rostade saltade", portion: 25, traits: ["over_10g_fat", "bile_stimulant", "fodmaps", "allergen_peanut", "cross_reactive"] },
      { name: "Salted Roasted Cashews", sv: "Saltade rostade cashewnötter", locked: true },
      { name: "Mixed Nuts (salted)", sv: "Blandade nötter (saltade)", locked: true }
    ]
  },
  {
    id: "readyMeals",
    label: "Ready Meals",
    sv: "Färdigmat",
    foods: [
      { name: "Frozen pizza", sv: "Fryst pizza", lmv: "Pizza orientalisk", portion: 175, traits: ["over_10g_fat", "bile_stimulant", "protein", "refined_carbs"] },
      { name: "French Fries (deep-fried)", sv: "Pommes frites (frityrkokta)", lmv: "Pommes frites friterad potatis fett ca 11% frysvara", portion: 150, traits: ["over_10g_fat", "bile_stimulant", "refined_carbs"] },
      { name: "French Fries (oven-baked)", sv: "Pommes frites (ugnsbakade)", locked: true },
      { name: "Instant Soup / Bouillon Cubes", sv: "Snabbsoppa / buljongtärningar", form: "cooked", lmv: "Köttbuljong tärning ätf.", lmvNote: "ready-to-eat broth, not the dry cube", portion: 200, traits: ["fodmaps", "allergen_celery"] },
      { name: "Instant Mashed Potato", sv: "Potatismospulver", locked: true },
      { name: "Dumplings", sv: "Dumplings", locked: true },
      { name: "Yellow Pea Soup with Pork", sv: "Ärtsoppa med fläsk", locked: true },
      { name: "Green Pea Soup", sv: "Ärtpurésoppa", locked: true },
      { name: "Fish Soup (bouillabaisse)", sv: "Fisksoppa (bouillabaisse)", locked: true },
      { name: "Shrimp Soup", sv: "Räksoppa", locked: true },
      { name: "Spring Roll", sv: "Vårrulle", locked: true }
    ]
  }
];

const CATEGORY_GROUPS = [
  {
    "title": "Produce",
    "sv": "Frukt & grönt",
    "categories": [
      "veggies",
      "fruits",
      "driedFruits",
      "berries",
      "roots",
      "mushrooms"
    ]
  },
  {
    "title": "Grains, Nuts & Legumes",
    "sv": "Spannmål, nötter & baljväxter",
    "categories": [
      "grains",
      "nuts",
      "legumes",
      "bread"
    ]
  },
  {
    "title": "Animal-Based",
    "sv": "Animaliskt",
    "categories": [
      "cheese",
      "seafood",
      "meat",
      "milkFermented",
      "offal",
      "charcuterie"
    ]
  },
  {
    "title": "Flavour & Extras",
    "sv": "Smak & tillbehör",
    "categories": [
      "spices",
      "condiments",
      "sauces",
      "dips",
      "sweetSpreads",
      "picklesFerments",
      "fats",
      "sweeteners"
    ]
  },
  {
    "title": "Processed & Drinks",
    "sv": "Processat & drycker",
    "categories": [
      "confectionery",
      "softDrinks",
      "bakedDesserts",
      "alcohol",
      "plantBased",
      "savourySnacks",
      "readyMeals"
    ]
  }
];
